<?php                             
$domain = $_SERVER['SERVER_NAME'];

if($_GET['sandbox']==1) $appPath = 'app_repository';
else $appPath = 'app';

// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../'.$appPath.'/libs/autoload.php';

$configurator = new Nette\Config\Configurator;         

// Enable Nette Debugger for error visualisation & logging
$configurator->setDebugMode(TRUE);
$configurator->enableDebugger(__DIR__ . '/../'.$appPath.'/log/'.$domain);

use Nette\Diagnostics\Debugger;
error_reporting(E_ALL ^ E_NOTICE);

// Specify folder for cache
$configurator->setTempDirectory(__DIR__ . '/../'.$appPath.'/temp/'.$domain);

// Enable RobotLoader - this will load all classes automatically
$configurator->createRobotLoader()	
  ->addDirectory(__DIR__ . '/../'.$appPath)
  ->addDirectory(__DIR__ . '/FrontModule')        	
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config.neon');
$container = $configurator->createContainer();

if($_GET['sandbox']==1) Debugger::enable(Debugger::DEVELOPMENT);  
else Debugger::enable(Debugger::PRODUCTION);      

Debugger::$email = 'info@pavelszabo.cz';
Debugger::$strictMode = FALSE;
Debugger::$maxDepth = 2; // default: 3
Debugger::$maxLen = 50; // default: 150

return $container;